
include $(COSIM_MK_DIR)/Makefile.sim

DEFINES += HAS_COSIM_MAIN
DEFINES += SIMULATION

XCELIUM_VFLAGS += $(addprefix +define+,$(DEFINES))
XCELIUM_VFLAGS += $(addprefix -D,$(DEFINES))
XCELIUM_VFLAGS += $(addprefix +incdir+,$(VINCLUDES))

XCELIUM_CFLAGS += $(CFLAGS)
XCELIUM_CFLAGS += -fPIC -std=c++14
XCELIUM_CFLAGS += $(addprefix -D,$(DEFINES))
XCELIUM_CFLAGS += $(addprefix -I,$(CINCLUDES))
XCELIUM_CFLAGS += $(addprefix -L,$(CLIBDIRS))

XCELIUM_LDFLAGS += $(LDFLAGS)
XCELIUM_LDFLAGS += -lpthread
XCELIUM_LDFLAGS += $(addprefix -L,$(CLIBDIRS))
XCELIUM_LDFLAGS += $(addprefix -l,$(CLIBS))

XCELIUM_BUILD_OPTS += -64bit
#XCELIUM_BUILD_OPTS += -notice
XCELIUM_BUILD_OPTS += -verbose
XCELIUM_BUILD_OPTS += +v2k -sv
XCELIUM_BUILD_OPTS += +lint=TFIPC-L
XCELIUM_BUILD_OPTS += -access +rwc
#XCELIUM_BUILD_OPTS += -assert svaext
XCELIUM_BUILD_OPTS += +noportcoerce
XCELIUM_BUILD_OPTS += -licqueue
#XCELIUM_BUILD_OPTS += -ldargs "$(XCELIUM_LDFLAGS)"
XCELIUM_BUILD_OPTS += -ccargs "$(XCELIUM_CFLAGS)"
XCELIUM_BUILD_OPTS += $(addprefix -I,$(CINCLUDES))
XCELIUM_BUILD_OPTS += $(XCELIUM_LDFLAGS)
XCELIUM_BUILD_OPTS += $(XCELIUM_VFLAGS)
XCELIUM_BUILD_OPTS += -cdslib /home/bli/projects/maxsdr/zynq-parrot/cosim/vivado/aurora_bd_proj.cache/compile_simlib/xcelium/cds.lib
XCELIUM_BUILD_OPTS += -hdlvar /home/bli/projects/maxsdr/zynq-parrot/cosim/vivado/aurora_bd_proj.cache/compile_simlib/xcelium/hdl.var


XCELIUM_BUILD_OPTS += -top $(TB_MODULE)
XCELIUM_BUILD_OPTS += -snapshot xbuild
XCELIUM_BUILD_OPTS += -elaborate -xmsc_msgs on
#XCELIUM_BUILD_OPTS += -timescale 1ps/1ps

#XCELIUM_RUN_OPTS += -no_save

ifeq ($(ENABLE_VERDI),1)
DUMP_FILE ?= dump.fsdb
else
DUMP_FILE ?= dump.vpd
endif

ifeq ($(ASSERT),1)
XCELIUM_BUILD_OPTS += +define+BSG_NONSYNTH_ASSERT_ENABLE
XCELIUM_BUILD_OPTS += -assert svaext # Enable elaboration system tasks
endif

ifneq (,$(TRACE))
RUN_ARGS += +bsg_trace=$(DUMP_FILE)
RUN_ARGS += +vpdfilesize+512
endif
run: ## runs the xbuild snapshot, TRACE=1 to trace
run: xbuild | $(RUN_COLLATERAL)
	$(XRUN) -R -snapshot $< $(XCELIUM_RUN_OPTS) $(RUN_ARGS) -input dump.tcl 2>&1 | $(TEE_I) run.log

ENABLE_VERDI ?= $(if $(shell which verdi 2> /dev/null),1,0)
ifneq (,$(TRACE))
BUILD_ARGS += -debug_access+r
BUILD_ARGS += +define+BSG_NONSYNTH_WAVEFORM_TRACER_ENABLE
BUILD_ARGS += +define+BSG_NONSYNTH_WAVEFORM_TRACER_DEPTH=0
BUILD_ARGS += +define+BSG_NONSYNTH_WAVEFORM_TRACER_HIER=bsg_nonsynth_zynq_testbench.dut
ifeq ($(ENABLE_VERDI),1)
BUILD_ARGS += +define+BSG_NONSYNTH_WAVEFORM_TRACER_FSDB
else
BUILD_ARGS += +define+BSG_NONSYNTH_WAVEFORM_TRACER_VPD
endif
endif

build: ## builds the xsim snapshot
build: xbuild
xbuild: $(VPACKAGES) $(VSOURCES) $(CSOURCES) | $(BUILD_COLLATERAL)
	$(XRUN) $(XCELIUM_BUILD_OPTS) $(BUILD_ARGS) $^ 2>&1 | $(TEE_I) build.log

view: ## views the dump with DVE
view: $(DUMP_FILE)
	@$(DVE) -full64 -vpd $< &

